	const_def $fc
	const OPP_GYM_LEAD
	const OPP_ELITE_FOUR
	const OPP_RIVAL
	const OPP_LIST_END


	const_def 1
	const MIN_BATTLES_RED
	const MIN_BATTLES_YELLOW
	const MIN_BATTLES_GYM_RUSH_RED
	const MIN_BATTLES_GYM_RUSH_YELLOW
	const MIN_BATTLES_BOSS_RUSH_RED
	const MIN_BATTLES_BOSS_RUSH_YELLOW


	const_def 6
	const BIT_MIN_BATTLES_OPTIONS_EVOLUTION
	const BIT_MIN_BATTLES_OPTIONS_NICKNAME
