name: Bug Report
description: File a bug report to help improve things for everyone.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What were you expecting to happen?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened to you?
    validations:
      required: true
  - type: textarea
    id: minimial-reproduction
    attributes:
      label: Minimal Reproduction
      description: The minimum list of steps required to reproduce the bug.
      placeholder: What is the shortest path to reproducing the bug?
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.0 (Default)
        - 0.4.0
        - 0.3.1
        - 0.3.0
        - 0.2.0
        - 0.1.1
        - 0.1.0
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: What systems are you seeing the problem on?
      multiple: true
      options:
        - "[Hardware] Game Boy"
        - "[Hardware] Game Boy Pocket"
        - "[Hardware] Game Boy Color"
        - "[Hardware] Game Boy Advance"
        - "[Hardware] Game Boy Player"
        - "[Hardware] Other"
        - "[Emulator] BGB"
        - "[Emulator] VisualBoyAdvance"
        - "[Emulator] Other"
    validations:
      required: true
